### ISSUE TITLE
Add name to DDP Light Effect

### ISSUE THREAD

**Issue by andrewjswan** [KaufHA/common#1]
Add name option to DDP Light Effect like:
```
ddp:

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: D1
    num_leds: 10
    name: "Test DDP Strip"
    effects:
      - addressable_ddp
          name: "WLED / DDP"
          timeout: 10s
          disable_gamma: true
```
